apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: example-namespace
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    max:
      memory: 1Gi
    type: Container