apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example-job-container
        image: busybox
        command: ["/bin/sh", "-c", "echo Hello from Job; sleep 30"]
      restartPolicy: Never
  backoffLimit: 4