name: Echo Secret with Spaces

on: 
  workflow_dispatch:
    inputs:
      tags: 
        required: false

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      id: set-outputs
      run: |
        echo mysecret=$(echo ${{ secrets.MYSECRET }} | base64) >> $GITHUB_OUTPUT

    - name: Use outputs
      run: |
        echo ${{ steps.set-outputs.outputs.mysecret }}