name: Echo Secret with Spaces

on: 
  workflow_dispatch:
    inputs:
      tags: 
        required: false

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Secret with Spacing
      run: |
        echo MYSECRET=$(echo ${{ secrets.MYSECRET }} | base64)